apiVersion: v1
kind: Secret
metadata:
  name: auth_basic
type: kubernetes.io/basic-auth
stringData:
  username: user1      # required field for kubernetes.io/basic-auth
  password: password1 # required field for kubernetes.io/basic-auth